#!/usr/bin/sh

# Bindings
sxhkd &

# Workspaces
bspc monitor VGA-1 -d I II III IV V VI

# Wallpaper
feh --bg-fill $HOME/.config/bspwm/sunscape.jpg

# Eww
eww -c $HOME/.config/eww/bar --restart open bar &


# Theme
bspc config normal_border_color "#676767"
bspc config active_border_color "#676767"
bspc config focused_border_color "#ce9492"
bspc config presel_feedback_color "#a7fbff"

# Gaps
bspc config border_width         6
bspc config window_gap           20

# Config
bspc config automatic_scheme      spiral
bspc config split_ratio           0.50

bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config single_monocle        true

bspc config focus_follows_pointer true
bspc config focused_frame_opacity 0.5
bspc config normal_frame_opacity  1

bspc config top_padding 75
bspc config left_padding 5
bspc config right_padding 4

